# Generated by Django 3.1.7 on 2021-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Email', models.TextField(max_length=120)),
                ('User_id', models.IntegerField()),
                ('Password1', models.CharField(max_length=120)),
                ('Password2', models.CharField(max_length=120)),
            ],
        ),
    ]
