# Generated by Django 3.1.7 on 2021-05-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='User_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
