# Generated by Django 3.1.7 on 2021-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0005_auto_20210502_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='LastName',
        ),
        migrations.AddField(
            model_name='patient',
            name='Username',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
