# Generated by Django 3.1.7 on 2021-05-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0006_auto_20210502_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='FullName',
        ),
    ]
