# Generated by Django 3.1.7 on 2021-05-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0008_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
